name: checks

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  links:
    name: links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: links
        run: |
          yarn install
          yarn lint:dead

  format:
    name: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: prettier
        run: |
          yarn install
          yarn lint:fmt

  spelling:
    name: spelling
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: cspell 
        run: |
           yarn install
           yarn lint:spell

  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: lint 
        run: |
            yarn install
            yarn lint:mdl